# Generated by Django 3.0.3 on 2020-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
